// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBO5Tvp_rpcxNn443exaG9VmIikqKhlLrE',
    appId: '1:935142790598:web:2d2050da70fdeb1c0d4ec7',
    messagingSenderId: '935142790598',
    projectId: 'diario-espiritual-642d0',
    authDomain: 'diario-espiritual-642d0.firebaseapp.com',
    storageBucket: 'diario-espiritual-642d0.firebasestorage.app',
    measurementId: 'G-7T2VLPEEQ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCidJZNGqD0GoiZMj25xcS5SiAf5QxC0ng',
    appId: '1:935142790598:android:64712904073ab6da0d4ec7',
    messagingSenderId: '935142790598',
    projectId: 'diario-espiritual-642d0',
    storageBucket: 'diario-espiritual-642d0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8lBeYwtA43aLc-_vyD3znP-SwGiDulOg',
    appId: '1:935142790598:ios:b0fa3409fc289df90d4ec7',
    messagingSenderId: '935142790598',
    projectId: 'diario-espiritual-642d0',
    storageBucket: 'diario-espiritual-642d0.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8lBeYwtA43aLc-_vyD3znP-SwGiDulOg',
    appId: '1:935142790598:ios:b0fa3409fc289df90d4ec7',
    messagingSenderId: '935142790598',
    projectId: 'diario-espiritual-642d0',
    storageBucket: 'diario-espiritual-642d0.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBO5Tvp_rpcxNn443exaG9VmIikqKhlLrE',
    appId: '1:935142790598:web:21440cc7e524eb0b0d4ec7',
    messagingSenderId: '935142790598',
    projectId: 'diario-espiritual-642d0',
    authDomain: 'diario-espiritual-642d0.firebaseapp.com',
    storageBucket: 'diario-espiritual-642d0.firebasestorage.app',
    measurementId: 'G-4QGKGKFXVJ',
  );
}
